# Generated by Django 4.1.7 on 2023-02-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_item_image_alter_sliderimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='price_after_sale',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='sale_percentage',
            new_name='price_before_sale',
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(upload_to='api/images/brands/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='api/images/categories/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='api/images/items/'),
        ),
        migrations.AlterField(
            model_name='sliderimage',
            name='image',
            field=models.ImageField(upload_to='api/images/sliders/'),
        ),
    ]
