# Generated by Django 4.1.7 on 2023-02-22 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_price_item_price_after_sale_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
