# Generated by Django 4.1.7 on 2023-02-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderimage',
            options={'verbose_name_plural': 'Slider Images'},
        ),
    ]
